Hierarhy 1.0
AnnaTayanova/EPAMLabs_04_21 pull request #3
Opened 2021-04-27 18:50 UTC by AnnaTayanova

2021-04-27 21:25 UTC, NikitaVarchenko requested changes
Разнести классы на разные файлы

2021-04-27 21:25 UTC, NikitaVarchenko commented on Hierarhy/Program.cs
> +namespace Hierarhy
Разнести на разные файлы

2021-04-29 20:18 UTC, AnnaTayanova commented on Hierarhy/Program.cs
> +namespace Hierarhy
Разнесено 28.04

2021-05-04 12:01 UTC, NikitaVarchenko approved these changes
Принял задание

2021-05-04 12:01 UTC, merged